name: example
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  fast_develop:
    path: ../

  # Toast插件 https://pub.flutter-io.cn/packages/oktoast
  oktoast: ^2.3.2

  #  https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.0.0-nullsafety.11

  # State https://pub.flutter-io.cn/packages/provider
  provider: ^5.0.0

  fast_mvvm: ^2.0.1

  fast_router: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

